services:
  poll:
    build: ./poll
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "5000:80"
    networks:
      - poll-tier
      - back-tier
    depends_on:
      - redis
    restart: always


  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - back-tier
    restart: always

  worker:
    build: ./worker
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: votes
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    networks:
      - back-tier
    depends_on:
      - redis
      - db
    restart: always


  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: votes
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - back-tier
    restart: always

  result:
    build: ./result
    ports:
      - "5001:80"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: votes
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    networks:
      - result-tier
      - back-tier
    depends_on:
      - db
    restart: always

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data:
